name: Auto Deploy to AWS Lambda

on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: |
          yarn global add serverless
          yarn
          
      - name: Run test
        run: |
          yarn lint
          yarn jest src/__tests__/.*/*.test.tsx?$

      - name: Deploy to Lambda
        run: |
          yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
